### ISSUE TITLE
[BUG] no reset invoice working

### ISSUE THREAD

**Issue by sekerea** [Artiom-Astashonak/school-accounting-studio#17]
I confirm that I've previously read bug reports, but I haven't found the solution or the report by other users.

Operating System: 10 Winda
Application version:  0.0.1
author is retarded no reset on invoice in woking

**Comment by Artiom-Astashonak** [comment]
I totally regret you having problems with School Accounting Studio and I'm going to solve this issue as soon as I can.

There is indeed a problem with `private void reset()` function of `InvoicePanel` class which doesn't account the existence of `SELLER_VAT_NUMBER`, `CUSTOMER_VAT_NUMBER`, and `INVOICE_PACKAGING_COST` fields. They should be added in the array of items to reset in order to function properly.

I thank you for your curiosity for my work and the time you spent on using my project.

As a result of coming refactoring and reformatting pull requests, I'll handle this problem.

**Comment by Artiom-Astashonak** [comment]
As commit 712eef6 on branch `updating/reformatting-refactoring` made on 08.02.2024 the issue is fixed.
